language: java

jdk:
  - oraclejdk8

matrix:
  fast_finish: true

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18c65e29b9926a658da8
    on_success: always
    on_failure: always
    on_start: always
