== Creating new project(s)

The link:{man}/golo-new.html[`golo new`] command can create new Golo project(s):

[source,sh]
----
$ golo new Foo
----

The command creates a new Golo module named `Foo` in a `main.golo` file with a simple __function__
named `main` that takes an argument for the JVM program arguments.

By default we create a new free-form project but you can specify the type of project with the
`--type` command argument. Three types of projects are currently available:

 * Free-form project,
 * Maven-driven project,
 * Gradle-driven project.

NOTE: The default value of the `--type` parameter can be changed by setting the `golo.new.type` property.

As an example if you want to create a Maven-driven project, just add `--type maven`:

[source,sh]
----
$ golo new Foo --type maven
----

By default we create the project directory where the `golo` command is run. If you need to create
your project directory elsewhere you can use the `--path` command argument:

[source,sh]
----
$ golo new Bar --path /opt/golo
----

This creates the project directory named `Bar` in `/opt/golo`.

=== Free-form project

The structure of a free-form project is as follows:

[source,sh]
----
$ tree Foo
Foo
├── imports
├── jars
└── main.golo
----

=== Maven-driven project

The structure of a Maven-driven project is as follows:

[source,sh]
----
$ tree Foo/
Foo/
├── pom.xml
├── README.md
└── src
    ├── main
    │   ├── golo
    │   │   └── main.golo
    │   └── resources
    └── test
        └── golo
----

The project can be built and packaged with Maven using the following command:
[source,sh]
----
$ mvn package
----

You can now run the module `Foo` with:

 * `mvn`

[source,sh]
----
$ mvn exec:java
----

 * `java`

[source,sh]
----
$ java -jar target/Foo-*-jar-with-dependencies.jar
----

 * `golo`

[source,sh]
----
$ cd target/classes
$ golo run --module Foo
----

=== Gradle-driven project

The structure of a Gradle-driven project is as follows:

[source,sh]
----
$ tree Foo/
Foo/
├── build.gradle
├── README.md
└── src
    ├── main
    │   ├── golo
    │   │   └── main.golo
    │   └── resources
    └── test
        └── golo
----

The project can be built and packaged with Gradle using the following command:
[source,sh]
----
$ gradle build
----

You can now run the module `Foo` with:

 * `gradle`

[source,sh]
----
$ gradle run
----

 * `golo`

[source,sh]
----
$ cd build/classes/main
$ golo run --module Foo
----

=== Version control

With the `--vcs` option, the command will create a _ignore_ file and try to initialize the repository. Mercurial (`hg`) and Git (`git`) are currently supported. For instance,

[source]
----
$ golo new --vcs git --type gradle Foo
$ tree -a -L 1 Foo/
Foo/
├── build.gradle
├── .git
├── .gitignore
├── README.md
└── src
$ cat Foo/.gitignore
*.class
build/
.gradle/
----

or

[source]
----
$ golo new --vcs hg --type maven Foo
$ tree -a -L 1 Foo/
Foo/
├── .hg
├── .hgignore
├── pom.xml
├── README.md
└── src
$ cat Foo/.hgignore
syntax: glob
*.class
target/
----

If the option is not given, or if the value is `none`, no repository is initialized.

NOTE: The default value of the `--vcs` parameter can be changed by setting the `golo.new.vcs` property.


=== Profile

The `--profile` option defines the kind of project you want to create, and will influence the files and hierarchy generated. Two profiles are currently supported:

- `app` will create a application project;
- `lib` will create a library project.


