OUTPUT = 'output'
MAIN = 'golo-guide.asciidoc'

task :default => [:all]

task :prepare do
  mkdir_p OUTPUT
end

desc "generates the HTML documentation"
task :html => [:prepare] do
  sh "asciidoc -b html5 -a icons -a toc2 -a iconsdir=`brew --prefix asciidoc`/etc/asciidoc/images/icons -a data-uri -a theme=flask -a source-highlighter=pygments -o output/index.html #{MAIN}"
end

desc "generates the PDF documentation"
task :pdf => [:prepare] do
  sh "a2x --verbose -L -f pdf --fop -D output --icons --icons-dir=`brew --prefix asciidoc`/etc/asciidoc/images/icons #{MAIN}"
end

desc "generates the HTML chunked documentation"
task :html_chunked => [:prepare] do
  sh "a2x --verbose -L -f chunked -D output #{MAIN}"
end

desc "generate all formats"
task :all => [:html, :pdf, :html_chunked]

desc "cleanup"
task :clean do
  rm_rf OUTPUT
end

