OUTPUT = 'output'

task :asciidoc_html => [:prepare] do
  sh "asciidoc -b html5 -a icons -a toc2 -a theme=flask -o output/index.html main.txt"
end

def extract_name(markdown_file)
  markdown_file[0..-10]
end

task :prepare do
  mkdir_p OUTPUT
end

task :clean do
  rm_rf OUTPUT
end

task :html => [:prepare] do
  Dir['*.markdown'].each do |src|
    name = extract_name(src)
    sh "pandoc --standalone --smart -t html5 -o #{OUTPUT}/#{name}.html #{src}"
  end
end
