OUTPUT = 'output'

task :prepare do
  mkdir_p OUTPUT
end

desc "generates the HTML documentation"
task :html => [:prepare] do
  sh "asciidoc -b html5 -a icons -a toc2 -a iconsdir=`brew --prefix asciidoc`/etc/asciidoc/images/icons -a data-uri -a theme=flask -a source-highlighter=pygments -o output/index.html main.asciidoc"
end

desc "cleanup"
task :clean do
  rm_rf OUTPUT
end

