name: Continuous integration and deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build distribution
      uses: actions/upload-artifact@v2
      with:
        name: Golo distribution from this build
        path: build/distributions/*.zip

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: .build/deploy.sh

